# Generated by Django 3.2.2 on 2021-08-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogb', '0005_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
